<a href="https://colab.research.google.com/github/willcosta29/Tratamento-de-Dados-de-Sal-rios-em-Data-Science/blob/main/Salary_categorization_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df_pd = pd.read_csv("Data_Science_Fields_Salary_Categorization.csv")
df_pd.head()

,Unnamed: 0,Working_Year,Designation,Experience,Employment_Status,Salary_In_Rupees,Employee_Location,Company_Location,Company_Size,Remote_Working_Ratio
0,1,2020,Data Scientist,MI,FT,"6,352,272.00",DE,DE,L,0
1,2,2020,Machine Learning Scientist,SE,FT,"20,688,070.00",JP,JP,S,0
2,3,2020,Big Data Engineer,SE,FT,"8,674,985.00",GB,GB,M,50
3,4,2020,Product Data Analyst,MI,FT,"1,591,390.00",HN,HN,S,0
4,5,2020,Machine Learning Engineer,SE,FT,"11,935,425.00",US,US,L,50

In [ ]:
df_pd['Salary_In_Rupees'] = df_pd['Salary_In_Rupees'].str.replace(',', '').astype(float)

In [ ]:
df_pd.head()

,Unnamed: 0,Working_Year,Designation,Experience,Employment_Status,Salary_In_Rupees,Employee_Location,Company_Location,Company_Size,Remote_Working_Ratio
0,1,2020,Data Scientist,MI,FT,6352272.0,DE,DE,L,0
1,2,2020,Machine Learning Scientist,SE,FT,20688070.0,JP,JP,S,0
2,3,2020,Big Data Engineer,SE,FT,8674985.0,GB,GB,M,50
3,4,2020,Product Data Analyst,MI,FT,1591390.0,HN,HN,S,0
4,5,2020,Machine Learning Engineer,SE,FT,11935425.0,US,US,L,50

In [ ]:
df_pd['Salary_In_Dollars'] = df_pd['Salary_In_Rupees'] / 90.60

In [ ]:
df_pd.head()

,Unnamed: 0,Working_Year,Designation,Experience,Employment_Status,Salary_In_Rupees,Employee_Location,Company_Location,Company_Size,Remote_Working_Ratio,Salary_In_Dollars
0,1,2020,Data Scientist,MI,FT,6352272.0,DE,DE,L,0,70113.377483
1,2,2020,Machine Learning Scientist,SE,FT,20688070.0,JP,JP,S,0,228345.143488
2,3,2020,Big Data Engineer,SE,FT,8674985.0,GB,GB,M,50,95750.386313
3,4,2020,Product Data Analyst,MI,FT,1591390.0,HN,HN,S,0,17565.011038
4,5,2020,Machine Learning Engineer,SE,FT,11935425.0,US,US,L,50,131737.582781

In [ ]:
df_pd['Experience'] = sqldf("""
                            SELECT
                              CASE Experience
                                WHEN 'EN' THEN 'Junior'
                                WHEN 'MI' THEN 'Pleno'
                                WHEN 'SE' THEN 'Senior'
                                WHEN 'EX' THEN 'Executive'
                                END AS Experience
                            FROM
                              df_pd
                            """)

In [ ]:
df_pd.head()

,Unnamed: 0,Working_Year,Designation,Experience,Employment_Status,Salary_In_Rupees,Employee_Location,Company_Location,Company_Size,Remote_Working_Ratio,Salary_In_Dollars
0,1,2020,Data Scientist,Pleno,FT,6352272.0,DE,DE,L,0,70113.377483
1,2,2020,Machine Learning Scientist,Senior,FT,20688070.0,JP,JP,S,0,228345.143488
2,3,2020,Big Data Engineer,Senior,FT,8674985.0,GB,GB,M,50,95750.386313
3,4,2020,Product Data Analyst,Pleno,FT,1591390.0,HN,HN,S,0,17565.011038
4,5,2020,Machine Learning Engineer,Senior,FT,11935425.0,US,US,L,50,131737.582781

In [ ]:
df_pd = sqldf(
              """
              SELECT
                working_year,
                Designation,
                Experience,
                Employment_Status,
                Salary_In_Dollars,
                Employee_Location,
                Company_Location,
                Company_Size,
                Remote_Working_Ratio
              FROM
                df_pd
              """
              )

In [ ]:
df_pd.head()

,Working_Year,Designation,Experience,Employment_Status,Salary_In_Dollars,Employee_Location,Company_Location,Company_Size,Remote_Working_Ratio
0,2020,Data Scientist,Pleno,FT,70113.377483,DE,DE,L,0
1,2020,Machine Learning Scientist,Senior,FT,228345.143488,JP,JP,S,0
2,2020,Big Data Engineer,Senior,FT,95750.386313,GB,GB,M,50
3,2020,Product Data Analyst,Pleno,FT,17565.011038,HN,HN,S,0
4,2020,Machine Learning Engineer,Senior,FT,131737.582781,US,US,L,50

In [ ]:
df_pd.to_csv('Data_Science_Salary.csv', index=False)